artist-id = "oh-my-girl/binnie"
kind = "single"

names = [
  { name = "μΈν°2020 OST", locale = "ko", original = true },
  { name = "Sseomtun 2020 OST", locale = "ko-Latn", default = true },
]

[[releases]]
released-on = "2020-06-16"
country = "KR"
media = [{ kind = "digital" }]
urls = [
  { url = "https://www.melon.com/album/detail.htm?albumId=10444814" },
]
