names = [
  { name = "μ‚¬μΈν (feat. Kid Milli) (prod. GroovyRoom)", locale = "ko", original = true },
  { name = "Sainhoe (feat. Kid Milli) (prod. GroovyRoom)", locale = "ko-Latn", default = true },
]
