artist-id = "the-boyz"
kind = "single"

names = [
  { name = "Christmassy!", locale = "ko", original = true, default = true },
]

[[releases]]
released-on = "2020-12-07"
country = "KR"
media = [{ kind = "digital" }]
urls = [
  { url = "https://www.melon.com/album/detail.htm?albumId=10529969" },
]
