artist-id = "lydia"
kind = "single"

names = [
  { name = "μΈν•μ μ§‘ OST Part.20", locale = "ko", original = true },
  { name = "Inhyeongui Jip OST Part.20", locale = "ko-Latn", default = true },
  { name = "Mysterious Personal Shopper OST Part.20", locale = "en" },
]

[[releases]]
released-on = "2018-07-14"
country = "KR"
media = [{ kind = "digital" }]
urls = [
  { url = "http://www.melon.com/album/detail.htm?albumId=10184909" },
]
