kind = "group"
started-on = "2019"
country = "KR"
gender = "female"

names = [
  { name = "κ±Έν¬λ¬μ‰¬", locale = "ko", original = true },
  { name = "GIRL CRUSH", locale = "ko-Latn", default = true },
]
