kind = "group"
started-on = "2017"
country = "KR"
gender = "female"

names = [
  { name = "μ„ν‚¤λ―Έν‚¤", locale = "ko", original = true },
  { name = "Weki Meki", locale = "ko-Latn", default = true },
]
