artist-id = "tarin"
kind = "ep"

names = [
  { name = "29", locale = "ko", original = true, default = true },
]

[[releases]]
released-on = "2020-10-17"
country = "KR"
media = [{ kind = "digital" }]
urls = [
  { url = "https://www.melon.com/album/detail.htm?albumId=10504756" },
]
