artist-id = "jhnovr"
kind = "single"

names = [
  { name = "If you...", locale = "ko", original = true, default = true },
]

[[releases]]
released-on = "2020-12-07"
country = "KR"
media = [{ kind = "digital" }]
urls = [
  { url = "https://www.melon.com/album/detail.htm?albumId=10529858" },
]
