names = [
  { name = "μΈνƒ€ (Lil' Something) (Inst.)", locale = "ko", original = true },
  { name = "Sseomta (Lil' Something) (Inst.)", locale = "ko-Latn", default = true },
]

artist-credits = [
  { artist-id = "vibe", separator = " X " },
  { artist-id = "exo/chen", separator = " X " },
  { artist-id = "heize" },
]
