names = [
  { name = "μΈνƒ€ (Lil' Something)", locale = "ko", original = true },
  { name = "Sseomta (Lil' Something)", locale = "ko-Latn", default = true },
]

artist_credits = [
  { artist_id = "vibe", separator = " x " },
  { artist_id = "exo/chen", separator = " x " },
  { artist_id = "heize" },
]

urls = [
  { url = "https://www.youtube.com/watch?v=Npxqg9p1Q94", name = "Music Video" },
]
