names = [
  { name = "μΈνƒ€ (Lil' Something) (Inst.)", locale = "ko", original = true },
  { name = "Sseomta (Lil' Something) (Inst.)", locale = "ko-Latn", default = true },
]

artist_credits = [
  { artist_id = "vibe", separator = " x " },
  { artist_id = "exo/chen", separator = " x " },
  { artist_id = "heize" },
]
