names = [
  { name = "Price of Pride", locale = "ja", original = true, default = true },
]

[[artist-credits]]
artist-id = "band-maid"
names = [
  { name = "BAND-MAIDÂ®", locale = "ja", original = true, default = true },
]
