kind = "person"
#started_on = ""
country = "KR"

names = [
  { name = "λ°•μ„Έν„", locale = "ko", kind = "real", original = true },
  { name = "Bak Se Hyeon", locale = "ko-Latn", kind = "real", default = true },
]
