kind = "person"
started-on = "1993-06-04"
country = "KR"

names = [
  { name = "EB", locale = "ko", kind = "stage", original = true, default = true },
  { name = "김은비", locale = "ko", kind = "real" },
]
