kind = "person"
# started-on = ""
country = "KR"
gender = "female"

names = [
  { name = "사야", locale = "ko", kind = "stage", original = true },
  { name = "SAya", locale = "ko-Latn", kind = "stage", default = true },
]
