kind = "group"
#started-on = ""
country = "KR"
gender = "male"

names = [
  { name = "μΈν‹°λ§", locale = "ko", kind = "stage", original = true },
  { name = "ULTIMA", locale = "ko-Latn", kind = "stage", default = true },
]
