kind = "person"
# started-on = ""
country = "KR"
gender = "male"

names = [
  { name = "ìœˆ", locale = "ko", kind = "stage", original = true },
  { name = "Wynn", locale = "ko-Latn", kind = "stage", default = true },
]
