kind = "person"
started-on = "1990-08-10"
country = "KR"
gender = "female"

names = [
  { name = "ì˜", locale = "ko", kind = "stage", original = true },
  { name = "YEL", locale = "ko-Latn", kind = "stage", default = true },
]
