names = [
  { name = "INTRO (After Midnight)", locale = "ko", original = true, default = true },
]

urls = [
  { url = "https://www.youtube.com/watch?v=1YWGV_wsUCo", name = "Official Audio" },
]

[[artist-credits]]
artist-id = "nine-muses/hyun-a"
names = [
  { name = "λ¬Έν„μ•„", locale = "ko", original = true },
  { name = "Moon Hyuna", locale = "ko-Latn", default = true },
]
