artist-id = "-virtual/vibe-x-chen-x-heize"
kind = "single"

names = [
  { name = "μΈνƒ€ (Lil' Something)", locale = "ko", original = true },
  { name = "Sseomta (Lil' Something)", locale = "ko-Latn", default = true },
]

artist-credits = [
  { artist-id = "vibe", separator = " x " },
  { artist-id = "exo/chen", separator = " x " },
  { artist-id = "heize" },
]

[[releases]]
released-on = "2016-04-08"
country = "KR"
media = [{ kind = "digital" }]
urls = [
  { url = "http://www.melon.com/album/detail.htm?albumId=2678416" },
  { url = "http://www.mnet.com/album/541101" },
  { url = "https://open.spotify.com/album/7gxKMQDoYwluKuL6orZQgl" },
]
