artist-id = "lee-aram"
kind = "ep"

names = [
  { name = "pale blue dot", locale = "ko", original = true, default = true },
]

[[releases]]
released-on = "2019-10-02"
country = "KR"
media = [{ kind = "digital" }]
urls = [
  { url = "https://www.melon.com/album/detail.htm?albumId=10334476" },
]
