names = [
  { name = "Så›", locale = "ja", original = true },
  { name = "S-kun", locale = "ja-Latn", default = true },
  { name = "Boy S", locale = "en" },
]

contributions = [
  { artist-id = "tsunku", kind = "lyricist" },
  { artist-id = "tsunku", kind = "composer" },
  { artist-id = "konishi-takao", kind = "arranger" },
]
