names = [
  { name = "GOOD GIRL", locale = "ko", original = true, default = true },
]

[[artist-credits]]
artist-id = "4minute/hyun-a"
names = [
  { name = "현아", locale = "ko", original = true },
  { name = "HyunA", locale = "ko-Latn", default = true },
]
