names = [
  { name = "μ—°μ• μ„Έν¬ (LOVE CELLS) (Inst.)", locale = "ko", original = true },
  { name = "Yeonaesepo (LOVE CELLS) (Inst.)", locale = "ko-Latn", default = true },
  { name = "LOVE CELLS (Inst.)", locale = "en" },
]
