kind = "person"
started-on = "1996-11-18"
country = "KR"

names = [
  { name = "ì†", locale = "ko", kind = "stage", original = true },
  { name = "Sorn", locale = "ko-Latn", kind = "stage", default = true },
  { name = "Chonnasorn Sajakul", locale = "th-Latn", kind = "real" },
]

[metadata]
blood-type = "A"
height = 164
weight = 48
