names = [
  { name = "Spell (Inst.)", locale = "ko", original = true, default = true },
]

[[artist-credits]]
artist-id = "sistar/hyo-rin"
names = [
  { name = "효린", locale = "ko", original = true },
  { name = "Hyolyn", locale = "ko-Latn", default = true },
]
